[project]
name = "vimeo-roku-live-injector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "certifi",
    "chardet",
    "click",
    "flask",
    "flask-cors",
    "future",
    "gunicorn",
    "idna",
    "itsdangerous",
    "jinja2",
    "markupsafe",
    "python-dotenv",
    "pytz",
    "pyvimeo",
    "requests",
    "six",
    "tinydb",
    "tuspy",
    "tzdata",
    "urllib3",
    "werkzeug",
    "youtube-dl",
]
